enum ErrorType {
  USER_INPUT_ERROR = "USER_INPUT_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_BLOCKED = "USER_BLOCKED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXIST = "USER_ALREADY_EXIST",
  EXPERIENCE_NOT_FOUND = "EXPERIENCE_NOT_FOUND",
  EDUCATION_NOT_FOUND = "EDUCATION_NOT_FOUND",
  SKILL_NOT_FOUND = "SKILL_NOT_FOUND",
  LANGUAGE_NOT_FOUND = "LANGUAGE_NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR = "NO_RESULT_FOUND",
}

export { ErrorType };
