# docker-compose up -d redis mongodb mysql postgres rabbitmq elasticsearch kibana
version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    # volumes:
    #   - ./docker-volumes/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
networks:
  postgres:
    name: postgres_network
