#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Preparing your project for commit: styling, testing, and building.'

# Check Prettier standards
npm run prettier:check ||
(
    echo '🚫 Your code styling does not meet the required standards.
            Prettier check failed. Please run npm run format, add the changes, and try committing again.';
    false;
)

# Check ESLint Standards
npm run lint:check ||
(
        echo '⚠️ Code quality issues detected by ESLint.
                ESLint check failed. Please make the required changes listed above, add the changes, and try committing again.'
        false; 
)

# Check tsconfig standards
# npm run types:check ||
# (
#     echo '⚠️ TypeScript type check failed.
#             Please make the required changes listed above.'
#     false;
# )

# # If everything passes... Now we can commit
# echo '👍 All checks passed. Attempting to build the project now.'

# Uncomment the build step if needed
# npm run build ||
# (
#     echo '❌ Build process failed.
#             Please review the errors above to understand why.'
#     false;
# )

# If everything passes... Now we can commit
# echo '✅ All checks passed. Committing your changes now.'

